const errorMessages = {
  internalError: 'Tivemos um erro interno, favor tentar novamente mais tarde',
  invalidUser: 'Email ou senha inv치lidos',
};

const errorTypes = {
  validationError: 'ValidationError',
  customError: 'CustomError',

};

// Written in PT because it will be the message to be displayed to the user on the front end
const validationErrors = {
  invalidEmail: 'E-mail inv치lido',
  invalidCPF: 'CPF inv치lido',
  invalidCNPJ: 'CNPJ inv치lido',
};

const responseMessages = {
  loginOK: 'Logado com sucesso',
};

module.exports = {
  errorMessages, validationErrors, responseMessages, errorTypes,
};
